### ISSUE TITLE
Missing setup-network-environment.service

### ISSUE THREAD

**Issue by gosharplite** [mhamrah/kubernetes-coreos-units#1]
Just curious on the creation of LEADER_ENDPOINT.

**Comment by gosharplite** [comment]
Ok, I got it.
```
It assumes there is an environment file at /etc/leader with a LEADER_ENDPOINT environment variable set. You can write to /etc/leader in your cloud-config when you bring up a node.
```

**Comment by gosharplite** [comment]
If I may put my two cents in, hard code kube-apiserver ip in ```kube-kubelet.service``` and ```kube-proxy.service``` might be easier than set LEADER_ENDPOINT in cloud-config.

**Comment by mhamrah** [comment]
Hey Tony, I see where you're coming from with the hard-coding than setting the LEADER_ENDPOINT. I originally hard-coded these values, but felt I had to make unnecessary changes when setting up clusters. Also, somewhat unrelated to Kubernetes, I found having a LEADER_ENDPOINT set (whether a list of ips for an ELB) benefits long-running clusters, especially on AWS, where the the leader nodes may change over time. By shifting this setting to a LEADER_ENDPOINT you no longer have to destroy/recreate the unit files to make changes.

**Comment by gosharplite** [comment]
Hi Michael, thanks for your clarification. I build k8s cluster on top of pure openstack and don't have AWS experience on this scenario.

**Comment by mhamrah** [comment]
I know OpenStack has cloud drive, which makes the cloud config a little easier. Anyway, I find minimizing changes to unit files a best-practice due to their immutable nature, and avoid hard coding ip's or other configuration when possible.

**Comment by gosharplite** [comment]
Me too, I try to avoid hard coding ip's or other configuration when possible. I'm in favor of minimizing cloud-config as much as possible. My cloud-confing for kubernetes nodes does two things, set up fleet and ssh_authorized_keys. All other actions are triggered by fleetctl.
In case the master node die, I can create a new master node, modify unit files and use fleetctl to re-configure all worker nodes without rebooting/recreating them.
